config/routes.rb
Rails.application.routes.draw do
  
	resources :distances, only: [:new, :create]
  resources :places, only: [:index, :new, :create, :show]
  root 'places#index'
end

app/models/place.rb
class Place < ActiveRecord::Base

	attr_accessor :raw_address

	geocoded_by :raw_address
	after_validation ->{
		self.raw_address = self.address
		geocode
	}, if: ->(obj){ obj.raw_address.present? && obj.raw_address != obj.address }
	# geocoded_by :address
	# after_validation :geocode, if: ->(obj){ obj.address.present? && obj.address_changed? }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode, unless: ->(obj){ obj.address.present? }, 
																		if: ->(obj){  obj.latitude.present? && obj.latitude_changed? && obj.longitude.present? && obj.longitude_changed? }

	scope :by_created_at, -> { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  def new
  	@places = Place.all
  end

  def create
  	@from = Place.find(params[:from])
  	@to = Place.find(params[:to])

  	if @to && @from
  		flash[:success] = "The distance from <strong>#{@from.title}</strong> to <strong>#{@to.title}</strong> is #{@from.distance_from(@to.to_coordinates)} km."
  		redirect_to new_distance_path
  	else
  		flash[:danger] = "The distance from <strong>#{@from.title}</strong> to <strong>#{@to.title}</strong> could not be calulate...:("
  		render :new
  	end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  	@places = Place.by_created_at
  end

  def show
  	@place = Place.find(params[:id])
  end

  def new
  	@place = Place.new
  end

  def create
  	@place = Place.new(place_params)

  	if @place.save!
  		redirect_to root_path, notice: 'Place added successfully!'
  	else
  		render :new
  	end
  end

  private
  	def place_params
  		params.require(:place).permit(:raw_address, :title, :visited_by, :longitude, :latitude)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/distances/new.html.erb
<h1 class="display-4">Measure Distance</h1>
<%= form_tag distances_path do %>
  <fieldset class="form-group">
  <%= label_tag 'from', 'From' %>
  <%= select_tag 'from', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
</fieldset>

  <fieldset class="form-group">
  <%= label_tag 'to', 'To' %>
  <%= select_tag 'to', options_from_collection_for_select(@places, :id, :title), class: "form-control" %>
</fieldset>

  <%= submit_tag 'Go!', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunWithGeocoder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5OJQyqH4vVdhtl5XdwcUqQUuReSyuKLU&callback=initMap" async defer></script>
</head>
<body>
	<nav class="navbar navbar-light bg-faded">
	  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
	    &#9776;
	  </button>
	  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
	  	<%= link_to("GeocoderFun", root_path, class: 'navbar-brand') %>
	    <ul class="nav navbar-nav">
	      <li class="nav-item <%= 'active' if current_page?(new_place_path) %>">
	      	<%= link_to('Add Place', new_place_path, class: "nav-link") %>
	      </li>
	      <li class="nav-item <%= 'active' if current_page?(new_distance_path) %>">
	        <%= link_to('Calculate Distances', new_distance_path, class: "nav-link") %>
	      </li>
	    </ul>
	  </div>
	</nav>
<br><br>


  

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg.html_safe, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for @place, html: { class: 'form-horizontal' } do |f| %>
	<%= f.input :title %>
	<%= f.input :visited_by %>
	<h4>Enter either an address or the coordinates</h4>
	<%= f.input :raw_address, label: 'Address' %>
	<small class="text-muted">You can also enter an IP. Your IP is <%= request.ip %></small>
	<div class="row">
		<div class="col-sm-3">
			<%= f.input :latitude, id: 'place_latitude' %>
		</div>
		<div class="col-sm-3">
			<%= f.input :longitude, id: 'place_longitude' %>
		</div>
		<div class="col-sm-3 padding-top">
			<%= link_to('Find on Map', '', class: "btn btn-info btn-xs", id: "find-on-map") %>
		</div>
	</div>
	<br><br>
	<%= f.button :submit, class: "btn btn-primary" %>
<% end %>
<br><br>
<div class="card">
  <div class="card-block" style="height:500px; width:100%;">
    <div id="map"></div>
  </div>
</div>

app/views/places/_place.html.erb
<div class='card'>
	<div class="card-block">
		<%= link_to(place.title, place_path(place)) %>
		visited by <strong><%= place.visited_by %></strong>
	</div>
</div>

app/views/places/create.html.erb
<h1>Places#create</h1>
<p>Find me in app/views/places/create.html.erb</p>

app/views/places/index.html.erb
<h1 class="display-4">Places</h1>
<%= link_to('Add Places', new_place_path, class: "btn btn-primary btn-lg") %>
<br><br>


<%= render @places %>

app/views/places/new.html.erb
<h1 class="display-4">Add a New Place</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<h1 class="display-4"><%= @place.title %></h1>
<p>Address: <%= @place.address %></p>
<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@place.latitude},#{@place.longitude}&markers=#{@place.latitude},#{@place.longitude}&zoom=7&size=640x400&key=AIzaSyC5OJQyqH4vVdhtl5XdwcUqQUuReSyuKLU",
              class: 'img-fluid img-rounded', alt: "#{@place.title} on the map" %>